"""initial corrected schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-10 23:20:02.645984
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_slots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_key', sa.String(length=64), nullable=False),
    sa.Column('placement', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('fill_type', sa.String(length=32), nullable=False),
    sa.Column('cpm_cpc', sa.Float(), nullable=False),
    sa.Column('min_bid', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_slots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_slots_slot_key'), ['slot_key'], unique=False)

    op.create_table('ai_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_id'), ['id'], unique=False)

    op.create_table('analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('dimension_value', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('content_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('traffic', sa.Float(), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('search', sa.Float(), nullable=False),
    sa.Column('social', sa.Float(), nullable=False),
    sa.Column('authority', sa.Float(), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_scores_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_scores_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_scores_id'), ['id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('trust_score', sa.BigInteger(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_decisions_target')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_updated_at'), ['updated_at'], unique=False)

    op.create_table('destination_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('destination_key', sa.String(length=128), nullable=False),
    sa.Column('reference_time', sa.String(length=27), nullable=False),
    sa.Column('total_publications', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('n_succeeded', sa.Integer(), nullable=False),
    sa.Column('n_failed', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'destination_key', 'reference_time', name='uq_destination_metrics_story_dest_time')
    )
    with op.batch_alter_table('destination_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_destination_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_metrics_destination_key'), ['destination_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_metrics_reference_time'), ['reference_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_destination_metrics_story_id'), ['story_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_id'), ['id'], unique=False)

    op.create_table('errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_errors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_errors_id'), ['id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.String(length=27), nullable=False),
    sa.Column('ended_at', sa.String(length=27), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_ended_at'), ['ended_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_started_at'), ['started_at'], unique=False)

    op.create_table('laws_regulations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('law_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('jurisdiction', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('effective_date', sa.String(length=27), nullable=True),
    sa.Column('text_summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laws_regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laws_regulations_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_laws_regulations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laws_regulations_law_id'), ['law_id'], unique=True)

    op.create_table('newsletters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('newsletter_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletters_newsletter_id'), ['newsletter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletters_slug'), ['slug'], unique=False)

    op.create_table('postpublish_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('publication_id', sa.String(length=36), nullable=True),
    sa.Column('reference_time', sa.String(length=27), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'story_id', 'reference_time', name='uq_postpublish_events')
    )
    with op.batch_alter_table('postpublish_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postpublish_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_postpublish_events_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postpublish_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postpublish_events_publication_id'), ['publication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postpublish_events_reference_time'), ['reference_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_postpublish_events_story_id'), ['story_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_story_id'), ['story_id'], unique=False)

    op.create_table('publication_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('destination_key', sa.String(length=128), nullable=False),
    sa.Column('reference_time', sa.String(length=27), nullable=False),
    sa.Column('n_attempts', sa.Integer(), nullable=False),
    sa.Column('n_succeeded', sa.Integer(), nullable=False),
    sa.Column('n_failed', sa.Integer(), nullable=False),
    sa.Column('latency_ms_min', sa.Float(), nullable=False),
    sa.Column('latency_ms_max', sa.Float(), nullable=False),
    sa.Column('latency_ms_avg', sa.Float(), nullable=False),
    sa.Column('first_attempt_at', sa.String(length=27), nullable=True),
    sa.Column('last_attempt_at', sa.String(length=27), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'destination_key', 'reference_time', name='uq_publication_metrics_story_dest_time')
    )
    with op.batch_alter_table('publication_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_destination_key'), ['destination_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_first_attempt_at'), ['first_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_last_attempt_at'), ['last_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_reference_time'), ['reference_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_metrics_story_id'), ['story_id'], unique=False)

    op.create_table('published_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('reference_time', sa.String(length=27), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.String(length=27), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'reference_time', name='uq_published_snapshots_story_time')
    )
    with op.batch_alter_table('published_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_reference_time'), ['reference_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_snapshots_story_id'), ['story_id'], unique=False)

    op.create_table('quality_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_quality_evaluations_target')
    )
    with op.batch_alter_table('quality_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_evaluations_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_evaluations_target_id'), ['target_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('trust_score', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked', sa.String(length=27), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_last_checked'), ['last_checked'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_source_id'), ['source_id'], unique=True)

    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trust_score', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_story_id'), ['story_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stories_updated_at'), ['updated_at'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_tool_id'), ['tool_id'], unique=True)

    op.create_table('trust_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('trust_score', sa.BigInteger(), nullable=False),
    sa.Column('source_trust', sa.BigInteger(), nullable=False),
    sa.Column('independent_corroboration', sa.BigInteger(), nullable=False),
    sa.Column('total_evidence', sa.BigInteger(), nullable=False),
    sa.Column('contradiction_penalty', sa.BigInteger(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('factors_json', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', name='uq_trust_evaluations_target')
    )
    with op.batch_alter_table('trust_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_evaluations_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evaluations_target_id'), ['target_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('salt', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('affiliate_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('network', sa.String(length=128), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=True),
    sa.Column('commission_pct', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_links_id'), ['id'], unique=False)

    op.create_table('ai_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('output_ref', sa.String(length=36), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_output_ref'), ['output_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_runs_run_id'), ['run_id'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=128), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('facts_json', sa.Text(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('opinion_json', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('read_time_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.String(length=27), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_article_id'), ['article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_updated_at'), ['updated_at'], unique=False)

    op.create_table('authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_id'), ['id'], unique=False)

    op.create_table('entity_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=36), nullable=False),
    sa.Column('predicate', sa.String(length=64), nullable=False),
    sa.Column('object_entity_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_relationships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relationships_object_entity_id'), ['object_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relationships_subject_entity_id'), ['subject_entity_id'], unique=False)

    op.create_table('generated_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('claim_refs_json', sa.Text(), nullable=True),
    sa.Column('excluded_claims_json', sa.Text(), nullable=True),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('deterministic', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('publishable', sa.Boolean(), nullable=False),
    sa.Column('validation_json', sa.Text(), nullable=True),
    sa.Column('reference_time', sa.String(length=27), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_artifacts_artifact_id'), ['artifact_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_reference_time'), ['reference_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_artifacts_updated_at'), ['updated_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_story_id'), ['story_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('as_of_date', sa.String(length=27), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_product_id'), ['product_id'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('destination_key', sa.String(length=128), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=192), nullable=False),
    sa.Column('published_at', sa.String(length=27), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.story_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_destination_key'), ['destination_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_publications_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_updated_at'), ['updated_at'], unique=False)

    op.create_table('review_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=True),
    sa.Column('claim_ids_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.Column('updated_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_tasks_updated_at'), ['updated_at'], unique=False)

    op.create_table('source_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=27), nullable=True),
    sa.Column('fetched_at', sa.String(length=27), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_dedupe_hash'), ['dedupe_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_items_source_id'), ['source_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('newsletter_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_newsletter_id'), ['newsletter_id'], unique=False)

    op.create_table('affiliate_clicks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_link_id', sa.String(length=36), nullable=False),
    sa.Column('user_agent_country', sa.String(length=8), nullable=True),
    sa.Column('clicked_at', sa.String(length=27), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_affiliate_link_id'), ['affiliate_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_id'), ['id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=True),
    sa.Column('story_id', sa.String(length=128), nullable=True),
    sa.Column('source_item_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('publication_date', sa.String(length=27), nullable=True),
    sa.Column('verified_at', sa.String(length=27), nullable=True),
    sa.Column('confidence', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_claim_id'), ['claim_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_claims_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_publication_date'), ['publication_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_source_item_id'), ['source_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_verified_at'), ['verified_at'], unique=False)

    op.create_table('publication_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('publication_id', sa.String(length=36), nullable=False),
    sa.Column('destination_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('distributed_at', sa.String(length=27), nullable=True),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'destination_key', name='uq_publication_attempts_pub_dest')
    )
    with op.batch_alter_table('publication_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_attempts_destination_key'), ['destination_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_attempts_distributed_at'), ['distributed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_attempts_publication_id'), ['publication_id'], unique=False)

    op.create_table('story_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.story_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_signals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_signals_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_signals_story_id'), ['story_id'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('source_item_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(length=27), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'source_item_id', name='uq_claim_evidence_claim_source')
    )
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_evidence_source_item_id'), ['source_item_id'], unique=False)

    op.create_table('fact_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.String(length=27), nullable=False),
    sa.Column('checker', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fact_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fact_checks_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_checks_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fact_checks_id'), ['id'], unique=False)

    # ### end Alembic commands ###

    # NewsForge schema-boundary metadata (_newsforge_meta) — managed admirably by
    # create_all elsewhere, but a migration-created DB must stamp it too so the
    # startup boundary (newsforge.db.schema) stays consistent with migrations.
    op.execute(
        "CREATE TABLE IF NOT EXISTS _newsforge_meta "
        "(key TEXT PRIMARY KEY, value TEXT NOT NULL)"
    )
    op.execute(
        "INSERT OR IGNORE INTO _newsforge_meta (key, value) VALUES ('schema_version', '1')"
    )
    op.execute(
        "INSERT OR IGNORE INTO _newsforge_meta (key, value) VALUES "
        "('applied_at', datetime('now'))"
    )


def downgrade() -> None:
    # Drop the schema-boundary metadata table last (unwind in reverse order).
    op.execute("DROP TABLE IF EXISTS _newsforge_meta")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fact_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fact_checks_id'))
        batch_op.drop_index(batch_op.f('ix_fact_checks_claim_id'))
        batch_op.drop_index(batch_op.f('ix_fact_checks_checked_at'))

    op.drop_table('fact_checks')
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_evidence_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_created_at'))
        batch_op.drop_index(batch_op.f('ix_claim_evidence_claim_id'))

    op.drop_table('claim_evidence')
    with op.batch_alter_table('story_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_signals_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_signals_item_id'))
        batch_op.drop_index(batch_op.f('ix_story_signals_id'))
        batch_op.drop_index(batch_op.f('ix_story_signals_created_at'))

    op.drop_table('story_signals')
    with op.batch_alter_table('publication_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_attempts_publication_id'))
        batch_op.drop_index(batch_op.f('ix_publication_attempts_id'))
        batch_op.drop_index(batch_op.f('ix_publication_attempts_distributed_at'))
        batch_op.drop_index(batch_op.f('ix_publication_attempts_destination_key'))
        batch_op.drop_index(batch_op.f('ix_publication_attempts_created_at'))

    op.drop_table('publication_attempts')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_verified_at'))
        batch_op.drop_index(batch_op.f('ix_claims_story_id'))
        batch_op.drop_index(batch_op.f('ix_claims_source_item_id'))
        batch_op.drop_index(batch_op.f('ix_claims_publication_date'))
        batch_op.drop_index(batch_op.f('ix_claims_id'))
        batch_op.drop_index(batch_op.f('ix_claims_claim_id'))
        batch_op.drop_index(batch_op.f('ix_claims_article_id'))

    op.drop_table('claims')
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_clicked_at'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_affiliate_link_id'))

    op.drop_table('affiliate_clicks')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_newsletter_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_source_items_id'))
        batch_op.drop_index(batch_op.f('ix_source_items_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_source_items_dedupe_hash'))

    op.drop_table('source_items')
    with op.batch_alter_table('review_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_story_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_decision_id'))
        batch_op.drop_index(batch_op.f('ix_review_tasks_created_at'))

    op.drop_table('review_tasks')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_updated_at'))
        batch_op.drop_index(batch_op.f('ix_publications_story_id'))
        batch_op.drop_index(batch_op.f('ix_publications_published_at'))
        batch_op.drop_index(batch_op.f('ix_publications_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_publications_id'))
        batch_op.drop_index(batch_op.f('ix_publications_destination_key'))
        batch_op.drop_index(batch_op.f('ix_publications_decision_id'))
        batch_op.drop_index(batch_op.f('ix_publications_created_at'))

    op.drop_table('publications')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_prices_id'))
        batch_op.drop_index(batch_op.f('ix_prices_as_of_date'))

    op.drop_table('prices')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_story_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('generated_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_updated_at'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_story_id'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_reference_time'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_id'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_decision_id'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_generated_artifacts_artifact_id'))

    op.drop_table('generated_artifacts')
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_relationships_subject_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_relationships_object_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_relationships_id'))

    op.drop_table('entity_relationships')
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_id'))

    op.drop_table('authors')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_articles_story_id'))
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_id'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_articles_article_id'))

    op.drop_table('articles')
    with op.batch_alter_table('ai_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_output_ref'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_id'))
        batch_op.drop_index(batch_op.f('ix_ai_runs_created_at'))

    op.drop_table('ai_runs')
    with op.batch_alter_table('affiliate_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_links_id'))

    op.drop_table('affiliate_links')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('trust_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_target_id'))
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_trust_evaluations_computed_at'))

    op.drop_table('trust_evaluations')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_tool_id'))
        batch_op.drop_index(batch_op.f('ix_tools_slug'))
        batch_op.drop_index(batch_op.f('ix_tools_id'))

    op.drop_table('tools')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_updated_at'))
        batch_op.drop_index(batch_op.f('ix_stories_story_id'))
        batch_op.drop_index(batch_op.f('ix_stories_slug'))
        batch_op.drop_index(batch_op.f('ix_stories_id'))
        batch_op.drop_index(batch_op.f('ix_stories_created_at'))

    op.drop_table('stories')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_sources_last_checked'))
        batch_op.drop_index(batch_op.f('ix_sources_id'))

    op.drop_table('sources')
    with op.batch_alter_table('quality_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_evaluations_target_id'))
        batch_op.drop_index(batch_op.f('ix_quality_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_quality_evaluations_computed_at'))

    op.drop_table('quality_evaluations')
    with op.batch_alter_table('published_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_snapshots_story_id'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_reference_time'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_published_at'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_published_snapshots_created_at'))

    op.drop_table('published_snapshots')
    with op.batch_alter_table('publication_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_metrics_story_id'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_reference_time'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_last_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_first_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_destination_key'))
        batch_op.drop_index(batch_op.f('ix_publication_metrics_created_at'))

    op.drop_table('publication_metrics')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_story_id'))
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.drop_index(batch_op.f('ix_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    op.drop_table('products')
    with op.batch_alter_table('postpublish_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postpublish_events_story_id'))
        batch_op.drop_index(batch_op.f('ix_postpublish_events_reference_time'))
        batch_op.drop_index(batch_op.f('ix_postpublish_events_publication_id'))
        batch_op.drop_index(batch_op.f('ix_postpublish_events_id'))
        batch_op.drop_index(batch_op.f('ix_postpublish_events_decision_id'))
        batch_op.drop_index(batch_op.f('ix_postpublish_events_created_at'))

    op.drop_table('postpublish_events')
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletters_slug'))
        batch_op.drop_index(batch_op.f('ix_newsletters_newsletter_id'))
        batch_op.drop_index(batch_op.f('ix_newsletters_id'))

    op.drop_table('newsletters')
    with op.batch_alter_table('laws_regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laws_regulations_law_id'))
        batch_op.drop_index(batch_op.f('ix_laws_regulations_id'))
        batch_op.drop_index(batch_op.f('ix_laws_regulations_effective_date'))

    op.drop_table('laws_regulations')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_started_at'))
        batch_op.drop_index(batch_op.f('ix_experiments_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_ended_at'))

    op.drop_table('experiments')
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_id'))
        batch_op.drop_index(batch_op.f('ix_errors_created_at'))

    op.drop_table('errors')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_id'))
        batch_op.drop_index(batch_op.f('ix_entities_entity_id'))

    op.drop_table('entities')
    with op.batch_alter_table('destination_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_destination_metrics_story_id'))
        batch_op.drop_index(batch_op.f('ix_destination_metrics_reference_time'))
        batch_op.drop_index(batch_op.f('ix_destination_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_destination_metrics_destination_key'))
        batch_op.drop_index(batch_op.f('ix_destination_metrics_created_at'))

    op.drop_table('destination_metrics')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_decisions_target_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_created_at'))

    op.drop_table('decisions')
    with op.batch_alter_table('content_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_scores_id'))
        batch_op.drop_index(batch_op.f('ix_content_scores_entity_id'))
        batch_op.drop_index(batch_op.f('ix_content_scores_computed_at'))

    op.drop_table('content_scores')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_analytics_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_entity_id'))

    op.drop_table('analytics')
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_created_at'))

    op.drop_table('ai_jobs')
    with op.batch_alter_table('ad_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_slots_slot_key'))
        batch_op.drop_index(batch_op.f('ix_ad_slots_id'))

    op.drop_table('ad_slots')
    # ### end Alembic commands ###